### ISSUE TITLE
Clarification Requested Re: Executing the Kubectl apply command

### ISSUE THREAD

**Issue by snyderdb** [saidsef/k8s-nifi-cluster#12]
hello, I wanted to see if you could be clearer on how this code should be executed.
I have an active kubernetes cluster running.

I have downloaded the code from this github page.

I have revised the ingress.yml and updated the host with a node from my K8s cluster.
spec:
  rules:
  - host: $(host -t NS hkddbs.net)

But, I am uclear how to execute the kubectl apply command.  Can you please provide any additional guidance?

Thank you

**Comment by saidsef** [comment]
@snyderdb Happy New Year and thanks for raising this issue!

I'd highly recommend that you use string rather than a variable i.e. `nifi.hkddbs.net` or something like it in the `host:` field, then you can deploy to Kubernetes via `kubectl apply -k deployment/`.

Depending on your usage requirements for NiFi you might want to increase the resources cpu/memory - the default values are for demo purposes.  Also, I have spotted the Ingress secret referenced was absent from the kustomizer, have fixed that now and created new tag/release [v2023.01](https://github.com/saidsef/k8s-nifi-cluster/tree/v2023.01).

**Comment by saidsef** [comment]
You seem to have run into the same issues as I have, my background is Platform/Infrastructure.  I have created this repo because I couldn't find a decent helm chart - also for my own need to understand how the different pieces of NiFi in clustered mode hang together - and one of the projects I was involved required NiFi deployments on different cloud platforms, I have reused this over the years.

There is a decent documentation on the Apache NiFi website, as a starting point I found these to be most helpful:
- https://nifi.apache.org/docs/nifi-docs/html/getting-started.html#i-started-nifi-now-what
- https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#build-a-custom-distribution

I hope those prove helpful!

**Comment by snyderdb** [comment]
Thanks Said Sent from my iPhoneOn Jan 2, 2023, at 6:01 PM, Said Sef ***@***.***> wrote:﻿
You seem to have run into the same issues as I have, my background is Platform/Infrastructure.  I have created this repo because I couldn't find a decent helm chart - also for my own need to understand how the different pieces of NiFi in clustered mode hang together - and one of the projects I was involved required NiFi deployments on different cloud platforms, I have reused this over the years.
There is a decent documentation on the Apache NiFi website, as a starting point I found these to be most helpful:

https://nifi.apache.org/docs/nifi-docs/html/getting-started.html#i-started-nifi-now-what
https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#build-a-custom-distribution

I hope those prove helpful!
